// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9IWR4-qfQ35V13ngHx0S7YMkzJcGI_g',
    appId: '1:163761724248:web:d0515d55ca5abca901232d',
    messagingSenderId: '163761724248',
    projectId: 'fcm-project-23861',
    authDomain: 'fcm-project-23861.firebaseapp.com',
    storageBucket: 'fcm-project-23861.firebasestorage.app',
    measurementId: 'G-PP36Z375HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhmuNZlEOtDsSLw7gu5UShsCBnH0SqJU',
    appId: '1:163761724248:android:3acf0a08e5a4d21901232d',
    messagingSenderId: '163761724248',
    projectId: 'fcm-project-23861',
    storageBucket: 'fcm-project-23861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNA5IRfkM-wlzjNwzlm8ifX7b7PVJrfI',
    appId: '1:163761724248:ios:9fd56bcbb907ab1e01232d',
    messagingSenderId: '163761724248',
    projectId: 'fcm-project-23861',
    storageBucket: 'fcm-project-23861.firebasestorage.app',
    iosBundleId: 'com.example.flutterFcmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu9IWR4-qfQ35V13ngHx0S7YMkzJcGI_g',
    appId: '1:163761724248:web:7679282b973689ef01232d',
    messagingSenderId: '163761724248',
    projectId: 'fcm-project-23861',
    authDomain: 'fcm-project-23861.firebaseapp.com',
    storageBucket: 'fcm-project-23861.firebasestorage.app',
    measurementId: 'G-EHD9C0LGW4',
  );
}
